export const CALENDAR_ADD_SLOT_REQUEST = 'CALENDAR_ADD_SLOT_REQUEST'
export const CALENDAR_ADD_SLOT_SUCCESS = 'CALENDAR_ADD_SLOT_SUCCESS'
export const CALENDAR_ADD_SLOT_FAIL = 'CALENDAR_ADD_SLOT_FAIL'

export const CALENDAR_REMOVE_SLOT = 'CALENDAR_REMOVE_SLOT'

export const CALENDAR_GET_ALL_SLOTS = 'CALENDAR_GET_ALL_SLOTS'

export const CALENDAR_EDIT_VACANT_SLOT_REQUEST = 'CALENDAR_EDIT_VACANT_SLOT_REQUEST'
export const CALENDAR_EDIT_VACANT_SLOT_SUCCESS = 'CALENDAR_EDIT_VACANT_SLOT_SUCCESS'
export const CALENDAR_EDIT_VACANT_SLOT_FAIL = 'CALENDAR_EDIT_VACANT_SLOT_FAIL'

export const FREELANCER_APPROVE_SLOT = 'FREELANCER_APPROVE_SLOT'
export const FREELANCER_REJECT_SLOT = 'FREELANCER_REJECT_SLOT'

export const FREELANCER_SLOTS_REQUEST = 'FREELANCER_SLOTS_REQUEST'
export const FREELANCER_SLOTS_SUCCESS = 'FREELANCER_SLOTS_SUCCESS'
export const FREELANCER_SLOTS_FAIL = 'FREELANCER_SLOTS_FAIL'

export const FREELANCER_REQUEST_SLOT = 'FREELANCER_REQUEST_SLOT'


