export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'

export const GET_USER_NOTIFICATIONS = 'GET_USER_NOTIFICATIONS'

export const FREELANCERS_LIST_REQUEST = 'FREELANCERS_LIST_REQUEST'
export const FREELANCERS_LIST_SUCCESS = 'FREELANCERS_LIST_SUCCESS'
export const FREELANCERS_LIST_FAIL = 'FREELANCERS_LIST_FAIL'

export const FREELANCER_DETAILS_REQUEST = 'FREELANCER_DETAILS_REQUEST'
export const FREELANCER_DETAILS_SUCCESS = 'FREELANCER_DETAILS_SUCCESS'
export const FREELANCER_DETAILS_FAIL = 'FREELANCER_DETAILS_FAIL'