const mainstyle = {
    headerRow: {
      marginTop: "2rem",
      marginLeft: "2rem",
      width: "100%",
    },
  
    DeliveryPickupgroup: {
      margin: "none",
      padding: "none",
      width: "11rem",
      fontFamily: "UberMoveText, sans-serif",
  
      backgroundColor: "#EEEEEE",
      borderRadius: "25px",
      height: "3.4rem",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    },
    DPButton: {
      borderRadius: "30px",
      backgroundColor: "#EEEEEE",
      boder: "none",
      color: "black",
      fontFamily: "UberMoveText, sans-serif",
      height: "2.5rem",
      width: "20px",
      padding: "0",
    },
    DpActiveButton: {
      borderRadius: "30px",
      backgroundColor: "white",
      color: "black",
      height: "2.5rem",
      width: "20px",
      fontFamily: "UberMoveText, sans-serif",
      padding: "0",
    },
    cart: {
      borderRadius: "30px",
      backgroundColor: "black",
      color: "white",
      // height: "2.5rem",
      height: "54.4 px",
      width: "7rem",
      paddingLeft: "10px",
    },
    location: {
      borderRadius: "30px",
      backgroundColor: "#EEEEEE",
      color: "black",
      height: "3.4rem",
      fontFamily: "UberMoveText, sans-serif",
      overflow: "hidden",
      width: "13rem",
      display: "flex",
      textOverflow: "ellipsis",
    },
    longlocation: {
      borderRadius: "30px",
      backgroundColor: "#EEEEEE",
      color: "black",
      height: "3.4rem",
      fontFamily: "UberMoveText, sans-serif",
      width: "20rem",
      display: "flex",
      alignItems: "center",
      alignContent: "center",
    },
    paddingLeft: {
      paddingLeft: "1rem",
    },
  };
  
  export default mainstyle;